spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_os
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  profiles:
    active: dev
  main:
    allow-circular-references: true

jwt:
  secret: ${JWT_SECRET:chave_super_secreta_com_pelo_menos_32_caracteres_para_atender_256_bits}
  expiration: 86400000 # 24 horas

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG
    com.sistemaos: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
